name       : pam
version    : 1.3.1
release    : 25
source     :
    - https://github.com/linux-pam/linux-pam/releases/download/v1.3.1/Linux-PAM-1.3.1.tar.xz : eff47a4ecd833fbf18de9686632a70ee8d0794b79aecb217ebd0ce11db4cd0db
license    : GPL-3.0-or-later
summary    : Pluggable Authentication Modules library
description: |
    The Linux PAM package contains Pluggable Authentication Modules used to enable the local system administrator to choose how applications authenticate users.
component  : system.base
emul32     : yes
devel      : true
builddeps  :
    - pkgconfig32(libattr)
    - pkgconfig32(libxcrypt)
    - pkgconfig(libtirpc)
    - acl-32bit-devel
    - bison-32bit-devel
    - db5-32bit-devel
    - flex-32bit-devel
patterns   :
    - 32bit :
        - /lib32
    - devel :
        - /usr/share/man/man3
setup      : |
    %patch -p1 < $pkgfiles/0001-pam_env-Support-a-stateless-configuration.patch
    %patch -p1 < $pkgfiles/0002-pam_shells-Support-stateless-shells-file.patch
    %patch -p1 < $pkgfiles/0001-Set-defaults-to-disable-core-dump-behavior-and-incre.patch
    %patch -p1 < $pkgfiles/0001-libpam-Keep-existing-pamdir-for-transition.patch
    %patch -p1 < $pkgfiles/0001-Backport-patch-from-Fedora-for-non-existent-user-che.patch

    if [[ ! -z "${EMUL32BUILD}" ]]; then
        %reconfigure --docdir=/usr/share/doc/Linux-PAM-$version \
                     --enable-securedir=/lib32/security \
                     --disable-nis
    else
        %reconfigure --docdir=/usr/share/doc/Linux-PAM-$version \
                     --enable-securedir=/lib/security \
                     --disable-nis
    fi
build      : |
    %make -j1
install    : |
    %make_install
    if [[ -z "${EMUL32BUILD}" ]]; then
        chmod 4755 $installdir/usr/sbin/unix_chkpwd
    fi
