name        : pam
version     : 1.1.6
release     : 6
source      :
    - http://linux-pam.org/library/Linux-PAM-1.1.6.tar.bz2 : bab887d6280f47fc3963df3b95735a27a16f0f663636163ddf3acab5f1149fc2
license     :
    - GPL-3.0
summary     : Pluggable Authentication Modules library
devel       : true
description : |
    The Linux PAM package contains Pluggable Authentication Modules used to enable the local system administrator to choose how applications authenticate users.
setup      : |
    %patch -p1 < $pkgfiles/Linux-PAM-1.1.6-destdir.patch
    %patch -p1 < $pkgfiles/pam_unix_enable_nullok.patch
    %configure --docdir=/usr/share/doc/Linux-PAM-1.1.6 \
               --enable-securedir=/lib/security \
               --disable-nis
build      : |
    %make
install    : |
    %make_install
    chmod 4755 $installdir/sbin/unix_chkpwd
