name        : pam
version     : 1.1.6
release     : 12
source      :
    - http://linux-pam.org/library/Linux-PAM-1.1.6.tar.bz2 : bab887d6280f47fc3963df3b95735a27a16f0f663636163ddf3acab5f1149fc2
license     :
    - GPL-3.0
summary     : Pluggable Authentication Modules library
description : |
    The Linux PAM package contains Pluggable Authentication Modules used to enable the local system administrator to choose how applications authenticate users.
component  : system.base
emul32     : yes
devel       : true
builddeps  :
    - glibc-32bit-devel
    - libgcc-32bit
    - bison-32bit-devel
    - flex-32bit-devel
    - flex-devel
    - attr-devel
    - attr-32bit-devel
    - acl-32bit-devel
    - acl-devel
patterns   :
    - 32bit:
        - /lib32
    - devel:
        - /usr/share/man/man3
setup      : |
    %patch -p1 < $pkgfiles/Linux-PAM-1.1.6-destdir.patch
    %patch -p1 < $pkgfiles/pam_unix_enable_nullok.patch
    %patch -p1 < $pkgfiles/0001-pam_env-Support-a-stateless-configuration.patch
    %patch -p1 < $pkgfiles/0002-pam_shells-Support-stateless-shells-file.patch
    %patch -p1 < $pkgfiles/0001-limits-Disable-core-dump-behaviour.patch
    autoreconf -vfi
    if [[ ! -z "${EMUL32BUILD}" ]]; then
        %configure --docdir=/usr/share/doc/Linux-PAM-1.1.6 \
                   --enable-securedir=/lib32/security \
                   --disable-nis
    else
        %configure --docdir=/usr/share/doc/Linux-PAM-1.1.6 \
                   --enable-securedir=/lib/security \
                   --disable-nis
    fi
build      : |
    %make -j1
install    : |
    %make_install
    if [[ -z "${EMUL32BUILD}" ]]; then
        chmod 4755 $installdir/sbin/unix_chkpwd
    fi
